version: '3.2'
services:
  # DB
  postgres:
    restart: always
    container_name: bochka-pg
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=bochka

  # BACK
  back:
    container_name: bochka-back
    build: ./back/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bochka
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - postgres
    expose:
      - '8080'
    ports:
      - '8080:8080'

  # FRONT
  front:
    container_name: bochka-front
    build: ./front
    ports:
      - '3000:3000'
